import { Link } from "react-router-dom";
import { motion } from "framer-motion";
import { FaSolarPanel, FaBatteryFull, FaLightbulb, FaChartBar, FaSave, FaTools } from "react-icons/fa";
import { Line, Bar, Pie, Doughnut } from "react-chartjs-2";
import { Chart as ChartJS, CategoryScale, LinearScale, PointElement, LineElement, BarElement, Title, Tooltip, Legend, ArcElement } from "chart.js";

// Register the required chart elements
ChartJS.register(CategoryScale, LinearScale, PointElement, LineElement, BarElement, ArcElement, Title, Tooltip, Legend);

const Welcome = () => {
    const cards = [
        {
            title: "Active Plates",
            description: "View active solar plates.",
            data: "120 Active",
            route: "/active-plates",
            icon: <FaSolarPanel />,
            chartType: "line", // Line chart
            graphData: [50, 60, 70, 80, 90], // Example data for Active Plates
        },
        {
            title: "Current Wastages",
            description: "Monitor current energy wastages.",
            data: "10.5 kWh",
            route: "/current-wastages",
            icon: <FaLightbulb />,
            chartType: "bar", // Bar chart
            graphData: [5, 6, 7, 8, 9], // Example data for Current Wastages
        },
        {
            title: "Power Generated",
            description: "Track power generated by your solar panels.",
            data: "350 kWh",
            route: "/power-generated",
            icon: <FaChartBar />,
            chartType: "line", // Line chart
            graphData: [300, 350, 400, 450, 500], // Example data for Power Generated
        },
        {
            title: "Energy Savings",
            description: "Track your energy savings with solar power.",
            data: "1,500 kWh",
            route: "/energy-savings",
            icon: <FaSave />,
            chartType: "pie", // Pie chart
            graphData: [30, 70], // Example data for Energy Savings
        },
        {
            title: "Battery Status",
            description: "Monitor your battery status and health.",
            data: "85% Charge",
            route: "/battery-status",
            icon: <FaBatteryFull />,
            chartType: "doughnut", // Doughnut chart
            graphData: [85, 15], // Example data for Battery Status (percentages)
        },
        {
            title: "Total System Monitored",
            description: "View the total system's performance.",
            data: "98% Performance",
            route: "/total-system-monitored",
            icon: <FaTools />,
            chartType: "bar", // Bar chart
            graphData: [95, 96, 97, 98, 99], // Example data for Total System Monitored
        },
    ];

    return (
        <div className="min-h-screen flex flex-col text-white font-funnel max-w-7xl mx-auto">
            <header className="mb-1 text-left">
                <h1 className="text-xl md:text-2xl font-funnel xl:text-3xl font-semibold mb-4 drop-shadow-lg">
                Solar Intelli Solutions Dashboard
                </h1>
            </header>
            <main className="grid grid-cols-1 sm:grid-cols-2 xl:grid-cols-3 gap-8 w-full">
                {cards.map((card, index) => (
                    <motion.div
                        key={index}
                        initial={{ opacity: 0, scale: 0.9 }}
                        animate={{ opacity: 1, scale: 1 }}
                        transition={{
                            duration: 0.5,
                            delay: index * 0.2,
                            ease: "easeInOut",
                        }}
                    >
                        <Link
                            to={card.route}
                            className="relative h-80 w-full bg-gradient-to-br from-[#0f1c47] via-[#1a275f] to-[#0f1c47] hover:brightness-110 transform transition duration-500 ease-in-out hover:scale-105 hover:rotate-3 rounded-lg shadow-2xl p-6 flex flex-col justify-between"
                        >
                            {/* Floating icon with hover animation */}
                            <div className="absolute top-4 right-4 text-gray-100 opacity-10 text-6xl rotate-12 hover:rotate-0 transition-transform duration-300">
                                {card.icon}
                            </div>
                            {/* Card Content */}
                            <div className="relative z-10 flex-grow">
                                <h2 className="text-xl md:text-2xl font-semibold text-white mb-2 drop-shadow-md">
                                    {card.title}
                                </h2>
                                <p className="text-sm text-gray-200 mb-2 flex-grow">
                                    {card.description}
                                </p>
                                <div className="text-lg font-semibold text-[#5B9B37] mb-4">
                                    {card.data}
                                </div>

                                {/* Graph Visualization */}
                                <div className="w-full h-32 mb-2 text-white">
                                    {card.chartType === "line" && (
                                        <Line
                                            data={{
                                                labels: ["Jan", "Feb", "Mar", "Apr", "May"], // X-axis labels
                                                datasets: [
                                                    {
                                                        label: card.title,
                                                        data: card.graphData,
                                                        borderColor: "#5B9B37",
                                                        backgroundColor: "rgba(91, 155, 55, 0.2)",
                                                        fill: true,
                                                    },
                                                ],
                                            }}
                                            options={{
                                                responsive: true,
                                                plugins: {
                                                    legend: {
                                                        position: "top",
                                                        labels: {
                                                            color: 'white', // White legend text
                                                        },
                                                    },
                                                    title: {
                                                        display: true,
                                                        text: `${card.title} Data`,
                                                        color: 'white', // White title text
                                                    },
                                                },
                                                scales: {
                                                    x: {
                                                        ticks: {
                                                            color: 'white', // White x-axis ticks
                                                        },
                                                    },
                                                    y: {
                                                        ticks: {
                                                            color: 'white', // White y-axis ticks
                                                        },
                                                    },
                                                },
                                            }}
                                        />
                                    )}

                                    {card.chartType === "bar" && (
                                        <Bar
                                            data={{
                                                labels: ["Jan", "Feb", "Mar", "Apr", "May"], // X-axis labels
                                                datasets: [
                                                    {
                                                        label: card.title,
                                                        data: card.graphData,
                                                        backgroundColor: "#5B9B37",
                                                    },
                                                ],
                                            }}
                                            options={{
                                                responsive: true,
                                                plugins: {
                                                    legend: {
                                                        position: "top",
                                                        labels: {
                                                            color: 'white', // White legend text
                                                        },
                                                    },
                                                    title: {
                                                        display: true,
                                                        text: `${card.title} Data`,
                                                        color: 'white', // White title text
                                                    },
                                                },
                                                scales: {
                                                    x: {
                                                        ticks: {
                                                            color: 'white', // White x-axis ticks
                                                        },
                                                    },
                                                    y: {
                                                        ticks: {
                                                            color: 'white', // White y-axis ticks
                                                        },
                                                    },
                                                },
                                            }}
                                        />
                                    )}

                                    {card.chartType === "pie" && (
                                        <Pie
                                            data={{
                                                labels: ["Savings", "Other"],
                                                datasets: [
                                                    {
                                                        label: card.title,
                                                        data: card.graphData,
                                                        backgroundColor: ["#5B9B37", "#f39c12"],
                                                    },
                                                ],
                                            }}
                                            options={{
                                                responsive: true,
                                                plugins: {
                                                    legend: {
                                                        position: "top",
                                                        labels: {
                                                            color: 'white', // White legend text
                                                        },
                                                    },
                                                    title: {
                                                        display: true,
                                                        text: `${card.title} Data`,
                                                        color: 'white', // White title text
                                                    },
                                                },
                                            }}
                                        />
                                    )}

                                    {card.chartType === "doughnut" && (
                                        <Doughnut
                                            data={{
                                                labels: ["Charge", "Remaining"],
                                                datasets: [
                                                    {
                                                        label: card.title,
                                                        data: card.graphData,
                                                        backgroundColor: ["#5B9B37", "#f39c12"],
                                                    },
                                                ],
                                            }}
                                            options={{
                                                responsive: true,
                                                plugins: {
                                                    legend: {
                                                        position: "top",
                                                        labels: {
                                                            color: 'white', // White legend text
                                                        },
                                                    },
                                                    title: {
                                                        display: true,
                                                        text: `${card.title} Data`,
                                                        color: 'white', // White title text
                                                    },
                                                },
                                            }}
                                        />
                                    )}
                                </div>

                                {/* Read More Button */}
                                {/* <button className="underline text-yellow-500 text-sm font-semibold hover:brightness-125 transform hover:scale-105 transition duration-300">
                                    Read More
                                </button> */}
                            </div>
                        </Link>
                    </motion.div>
                ))}
            </main>
        </div>
    );
};

export default Welcome;
